# Generated by Django 4.2.6 on 2024-05-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
