# Generated by Django 4.2.6 on 2024-05-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
