# Generated by Django 4.2.6 on 2024-05-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='AboutUs',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['title'], 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
