# Generated by Django 4.2.6 on 2024-05-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bang', '0005_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
