# Generated by Django 4.2.6 on 2023-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baimed', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=10, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
