# Generated by Django 4.2.6 on 2023-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baimed', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.TextField(blank=True, verbose_name='Номер телефона')),
                ('code', models.DateTimeField(auto_now_add=True, verbose_name='Код')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'ordering': ['time_create'],
            },
        ),
    ]
