# Generated by Django 4.2.6 on 2025-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='organisation',
            field=models.TextField(blank=True, verbose_name='Организация'),
        ),
    ]
