# Generated by Django 4.2.6 on 2025-01-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointments_status_alter_appointments_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='service_type',
            field=models.CharField(default=11, max_length=255, verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Пациент записан'), ('completed', 'Приём выполнен'), ('cancelled', 'Приём отменён')], default='scheduled', max_length=10, verbose_name='Статус'),
        ),
    ]
